### ISSUE TITLE
Deploy without creating App Service Plan

### ISSUE THREAD

**Issue by wub** [solvsoftware/Ghost-Azure#12]
First, thanks so much for making this!

I'm a little overwhelmed by the deploymentTemplate JSON. Is there an easy way to either:

- Edit the deployment JSON to add to an existing App Service Plan, instead of creating a new one, or,
- Deploy it myself by adding the repo as a "Deployment option"? And if so, are there any settings (siteName, email settings) that I need to add manually?

Thanks!

**Comment by RadoslavGatev** [comment]
Absolutely, there's such a way.
I personally did the same thing for my blog as I had an existing app service plan. So I modified the resource template in such a way to create a Web App belonging to my existing App Service Plan.

As you said you can manually configure it as a Deployment option and technically that's what the template would do behind the scenes:
1. Create a Web App using the Azure Portal.
2. Configure the Deployment option to point to your fork of Ghost-Azure.
3. Enter the following App Settings: https://github.com/solvsoftware/Ghost-Azure/blob/1ab7e814bda6744d3921d8ac758a45653161b018/azuredeploy.json#L114-L121 
4. Follow the [Post-deployment configuration steps](https://www.gatevnotes.com/ghost-on-azure-app-service/#postdeploymentconfigurations)
