### ISSUE TITLE
Deploy to Azure button creating new App Service Plans

### ISSUE THREAD

**Issue by davidleechen** [solvsoftware/Ghost-Azure#14]
Hello,

Is it possible to configure the deploy to Azure button to not create a new App Service Plan? I would want to deploy to existing App service plans.

Thanks for your work.

**Comment by wub** [comment]
Check this out - https://github.com/solvsoftware/Ghost-Azure/issues/12

**Comment by davidleechen** [comment]
Thanks, if it worked for you.

**Comment by davidleechen** [comment]
For anyone who comes here, I ended up going the easier route and just using the Deployment Options deployment type with External Repository set to this repo and the azure branch.
