### ISSUE TITLE
Is there a way to use ghost CLI to run locally for debugging/customization?

### ISSUE THREAD

**Issue by briannoyes** [solvsoftware/Ghost-Azure#22]
I'd like to be able to make changes directly in my branch that I use to deploy to Azure. But ghost start at the command line in the root folder doesn't work. So for now I have a separate instance of ghost in a separate repo and have to move the changes between the two branches manually (using my diff tool).

**Comment by RadoslavGatev** [comment]
I don't think so. I've tried multiple times to use the Ghost CLI as a baseline for this repo but it didn't work well.
What kind of changes do you need to apply for example?

**Comment by briannoyes** [comment]
OK, not a big deal, was just making sure I wasn't missing anything. In my case it was that I was redeploying my blog after upgrading to Ghost 2 and had a few iterations of making tweaks to the theme after my initial deployment, which I wanted to test locally before deploying. So I just had a separate repo that I generated a Ghost instance into, made my tweaks there, tested, and then used a diff tool (Beyond Compare in my case) to move those changes into the Ghost-Azure repo for deployment. 

Just wanted to see if there was a way to eliminate the file sync part of that process.
