### ISSUE TITLE
Error when upgrading from 1.x to 2x

### ISSUE THREAD

**Issue by dmoore44** [solvsoftware/Ghost-Azure#24]
Hi, when I hit the 'sync' button in Azure, the upgrade process kicks off, but then fails after a few minutes. I am getting the following error(s): 

```
Error: SQLITE_ERROR: table posts has no column named comment_id
Command 'starter.cmd deploy.cmd' was aborted due to no output nor CPU activity for 60 seconds. You can increase the SCM_COMMAND_IDLE_TIMEOUT app setting (or WEBJOBS_IDLE_TIMEOUT if this is a WebJob) if needed.\r\nstarter.cmd deploy.cmd
One or more errors occurred.
Command 'starter.cmd deploy.cmd' was aborted due to no output nor CPU activity for 60 seconds. You can increase the SCM_COMMAND_IDLE_TIMEOUT app setting (or WEBJOBS_IDLE_TIMEOUT if this is a WebJob) if needed.\r\nstarter.cmd deploy.cmd
```

**Comment by RadoslavGatev** [comment]
Hi,

I haven't had this issue. You may want to understand what's happening by reviewing what's in the database file and what's about to be executed against it.
I had a similar issue. You can read about it here: https://www.gatevnotes.com/introducing-ghost-2-on-azure-web-app-service/
