### ISSUE TITLE
Question (not a issue)

### ISSUE THREAD

**Issue by nitinkhosla79** [solvsoftware/Ghost-Azure#25]
We have a static website and blog site. We want to combine them. How to combine this repo(ghost-azure) with website repo we maintain. 
Both our sites are hosted on azure. Please advise (steps).  

Thanks to the team who created this repo. We tried setting up ghost manually on azure portal and spent hours without success. This was one click.

**Comment by RadoslavGatev** [comment]
I am not sure how your static website and the blog should coexist. You can probably deploy them as two standalone web apps or as virtual directories inside a single web app - https://blogs.msdn.microsoft.com/benjaminperkins/2017/10/27/how-to-map-an-azure-app-service-web-app-virtual-directory-to-azure-storage-containter/ 
That's what I can suggest without knowing any further details.
