### ISSUE TITLE
(Question) How to update deployed site/blog

### ISSUE THREAD

**Issue by killer-frog** [solvsoftware/Ghost-Azure#26]
I've been playing with ghost and found this repo awesome for getting ghost running on my azure.

I have now tweaked some of my css and want to  upload these amendments to azure.  However the deploy button tries to create a new site, if I specify my current site it errors that the site already exists.

Thanks Ash.

**Comment by RadoslavGatev** [comment]
The deployment button is mainly to get started quickly.
You have to configure the web app to sync with your own repo. It's in your Azure Web App > Deployment center.
