### ISSUE TITLE
Rewrite rule causing too many redirects

### ISSUE THREAD

**Issue by thiagospassos** [solvsoftware/Ghost-Azure#28]
I've deployed recently to Azure and I was getting the error "Too many redirects" and accessed via HTTPS configured outside Azure (through CloudFlare). 

Removing the lines below from the web.config solved the issue

```
<rule name="HTTP to HTTPS redirect" stopProcessing="true">
	<match url="(.*)" />
	<conditions>
		<add input="{HTTPS}" pattern="off" ignoreCase="true" />
	</conditions>
	<action type="Redirect" url="https://{HTTP_HOST}/{R:1}" redirectType="Permanent" />
</rule>
```

**Comment by RadoslavGatev** [comment]
Thanks for pointing this out!
