### ISSUE TITLE
Sync in Azure deployment center completely broke site

### ISSUE THREAD

**Issue by bdelaney** [solvsoftware/Ghost-Azure#30]
I'm trying to troubleshoot why my first sync after my initial deploy last October has taken the site down completely. The deployment center log does not help. Node version changes do not help. I wonder if it's because I added a custom them when I set it up in October.
Any hints on troubleshooting further? I have looked at the downloaded SQLite database.
I'll only be losing a few articles I posted if I start over...

**Comment by RadoslavGatev** [comment]
I guess it's too late for you but you can take a look at the logs of the deployment that broke the website.
