### ISSUE TITLE
Question: How to change default url?

### ISSUE THREAD

**Issue by georgeedwards** [solvsoftware/Ghost-Azure#31]
I installed my site on Azure as per this project. The installation has worked well, but picked up the azure url [`ghost-azure5ed4.azurewebsites.net1`](ghost-azure5ed4.azurewebsites.net). I have added a custom url to the project, whihc is working, but the meta data e.g. canonical links and home buttons still route to the azure url. 

Is there any way I can change this properly?

**Comment by KonttiAntti** [comment]
Ghost reads real URL from url named application settings, what you can found in web app's Configuration.
![image](https://user-images.githubusercontent.com/33060281/65722438-f0312b00-e0b4-11e9-98be-aa2a7c8a6abe.png)
