### ISSUE TITLE
Azure Deploy Not working for me.

### ISSUE THREAD

**Issue by Treyphor** [solvsoftware/Ghost-Azure#32]
Getting this error when it tries to deploy:
`Command: deploy.cmd
Handling node.js deployment.
Creating app_offline.htm
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
Copying file: 'iisnode.yml'
Deleting app_offline.htm
Using start-up script index.js from package.json.
Node.js versions available on the platform are: 0.6.20, 0.8.2, 0.8.19, 0.8.26, 0.8.27, 0.8.28, 0.10.5, 0.10.18, 0.10.21, 0.10.24, 0.10.26, 0.10.28, 0.10.29, 0.10.31, 0.10.32, 0.10.40, 0.12.0, 0.12.2, 0.12.3, 0.12.6, 4.0.0, 4.1.0, 4.1.2, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.3.0, 4.3.2, 4.4.0, 4.4.1, 4.4.6, 4.4.7, 4.5.0, 4.6.0, 4.6.1, 4.8.4, 5.0.0, 5.1.1, 5.3.0, 5.4.0, 5.5.0, 5.6.0, 5.7.0, 5.7.1, 5.8.0, 5.9.1, 6.0.0, 6.1.0, 6.2.2, 6.3.0, 6.5.0, 6.6.0, 6.7.0, 6.9.0, 6.9.1, 6.9.2, 6.9.4, 6.9.5, 6.10.0, 6.10.3, 6.11.1, 6.11.2, 6.11.5, 6.12.2, 6.12.3, 7.0.0, 7.1.0, 7.2.0, 7.3.0, 7.4.0, 7.5.0, 7.6.0, 7.7.0, 7.7.4, 7.10.0, 7.10.1, 8.0.0, 8.1.4, 8.4.0, 8.5.0, 8.7.0, 8.8.0, 8.8.1, 8.9.0, 8.9.3, 8.9.4, 8.10.0, 8.11.1, 10.0.0, 10.6.0, 10.14.1, 10.15.2.
Selected node.js version 10.15.2. Use package.json file to choose a different version.
Selected npm version 6.4.1
Updating iisnode.yml at D:\home\site\wwwroot\iisnode.yml
npm WARN deprecated superagent@3.8.3: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN bookshelf@0.14.2 requires a peer of knex@>=0.6.10 <0.15.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-stripe-elements@2.0.3 requires a peer of react@^15.5.4 || ^16.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN react-stripe-elements@2.0.3 requires a peer of react-dom@^15.5.4 || ^16.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! path D:\home\site\wwwroot\core\shared\nql-map-key-values
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall symlink
npm ERR! Error: EPERM: operation not permitted, symlink 'D:\home\site\wwwroot\core\shared\nql-map-key-values' -> 'D:\home\site\wwwroot\node_modules\nql-map-key-values'
npm ERR!  { [Error: EPERM: operation not permitted, symlink 'D:\home\site\wwwroot\core\shared\nql-map-key-values' -> 'D:\home\site\wwwroot\node_modules\nql-map-key-values']
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, symlink 'D:\home\site\wwwroot\core\shared\nql-map-key-values' -> 'D:\home\site\wwwroot\node_modules\nql-map-key-values'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'symlink',
npm ERR!      path: 'D:\\home\\site\\wwwroot\\core\\shared\\nql-map-key-values',
npm ERR!      dest: 'D:\\home\\site\\wwwroot\\node_modules\\nql-map-key-values' },
npm ERR!   stack:
npm ERR!    'Error: EPERM: operation not permitted, symlink \'D:\\home\\site\\wwwroot\\core\\shared\\nql-map-key-values\' -> \'D:\\home\\site\\wwwroot\\node_modules\\nql-map-key-values\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'symlink',
npm ERR!   path: 'D:\\home\\site\\wwwroot\\core\\shared\\nql-map-key-values',
npm ERR!   dest: 'D:\\home\\site\\wwwroot\\node_modules\\nql-map-key-values',
npm ERR!   parent: 'ghost' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
Failed exitCode=-4048, command="D:\Program Files (x86)\nodejs\10.15.2\node.exe" "D:\Program Files (x86)\npm\6.4.1\node_modules\npm\bin\npm-cli.js" install --production
npm ERR! the command again as root/Administrator (though this is not recommended).
An error has occurred during web site deployment.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\local\AppData\npm-cache\_logs\2019-08-14T16_46_21_838Z-debug.log
npm WARN deprecated superagent@3.8.3: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released.\r\nnpm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.\r\nnpm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.\r\nnpm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.\r\nnpm WARN bookshelf@0.14.2 requires a peer of knex@>=0.6.10 <0.15.0 but none is installed. You must install peer dependencies yourself.\r\nnpm WARN react-stripe-elements@2.0.3 requires a peer of react@^15.5.4 || ^16.0.0-0 but none is installed. You must install peer dependencies yourself.\r\nnpm WARN react-stripe-elements@2.0.3 requires a peer of react-dom@^15.5.4 || ^16.0.0-0 but none is installed. You must install peer dependencies yourself.\r\nnpm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.\r\n\r\nnpm ERR! path D:\home\site\wwwroot\core\shared\nql-map-key-values\r\nnpm ERR! code EPERM\r\nnpm ERR! errno -4048\r\nnpm ERR! syscall symlink\r\nnpm ERR! Error: EPERM: operation not permitted, symlink 'D:\home\site\wwwroot\core\shared\nql-map-key-values' -> 'D:\home\site\wwwroot\node_modules\nql-map-key-values'\r\nnpm ERR!  { [Error: EPERM: operation not permitted, symlink 'D:\home\site\wwwroot\core\shared\nql-map-key-values' -> 'D:\home\site\wwwroot\node_modules\nql-map-key-values']\r\nnpm ERR!   cause:\r\nnpm ERR!    { Error: EPERM: operation not permitted, symlink 'D:\home\site\wwwroot\core\shared\nql-map-key-values' -> 'D:\home\site\wwwroot\node_modules\nql-map-key-values'\r\nnpm ERR!      errno: -4048,\r\nnpm ERR!      code: 'EPERM',\r\nnpm ERR!      syscall: 'symlink',\r\nnpm ERR!      path: 'D:\\home\\site\\wwwroot\\core\\shared\\nql-map-key-values',\r\nnpm ERR!      dest: 'D:\\home\\site\\wwwroot\\node_modules\\nql-map-key-values' },\r\nnpm ERR!   stack:\r\nnpm ERR!    'Error: EPERM: operation not permitted, symlink \'D:\\home\\site\\wwwroot\\core\\shared\\nql-map-key-values\' -> \'D:\\home\\site\\wwwroot\\node_modules\\nql-map-key-values\'',\r\nnpm ERR!   errno: -4048,\r\nnpm ERR!   code: 'EPERM',\r\nnpm ERR!   syscall: 'symlink',\r\nnpm ERR!   path: 'D:\\home\\site\\wwwroot\\core\\shared\\nql-map-key-values',\r\nnpm ERR!   dest: 'D:\\home\\site\\wwwroot\\node_modules\\nql-map-key-values',\r\nnpm ERR!   parent: 'ghost' }\r\nnpm ERR! \r\nnpm ERR! The operation was rejected by your operating system.\r\nnpm ERR! It's possible that the file was already in use (by a text editor or antivirus),\r\nnpm ERR! or that you lack permissions to access it.\r\nnpm ERR! \r\nnpm ERR! If you believe this might be a permissions issue, please double-check the\r\nnpm ERR! permissions of the file and its containing directories, or try running\r\nnpm ERR! the command again as root/Administrator (though this is not recommended).\r\n\r\nnpm ERR! A complete log of this run can be found in:\r\nnpm ERR!     D:\local\AppData\npm-cache\_logs\2019-08-14T16_46_21_838Z-debug.log\r\nD:\Program Files (x86)\SiteExtensions\Kudu\82.10503.3890\bin\Scripts\starter.cmd deploy.cmd`

**Comment by UlrichGB** [comment]
I get the exact same error when deploying the new build.

**Comment by Treyphor** [comment]
Update on this: http://disq.us/p/23qqt2o Should be fixed when the next version of ghost is released.
