### ISSUE TITLE
deploy.azure.com is not responding. ERROR: DNS_PROBE_FINISHED_NXDOMAIN

### ISSUE THREAD

**Issue by rohitsaini1196** [solvsoftware/Ghost-Azure#40]
Well
I know this issue is with Azure itself but is there any other way of direct deployment?

Obvious answer is via portal BUT while deploying through Azure portal, this repo and major branch (azure) is giving errors.

**Comment by RadoslavGatev** [comment]
I guess this was an intermittent issue.
