### ISSUE TITLE
AzureDeploy not working

### ISSUE THREAD

**Issue by SimonDarksideJ** [solvsoftware/Ghost-Azure#42]
Tried clicking on the Azure Deploy option and it simply reports a 404 error

**Comment by SimonDarksideJ** [comment]
Seems the Azure deploy path has changed, info here:
https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-to-azure-button

**Comment by SimonDarksideJ** [comment]
When fixing the URL link to use the new method, it also reports there is an error with the AzureDeploy.json configuration and is unable to launch

**Comment by RadoslavGatev** [comment]
The azuredeploy.net seems to be deprecated although I cannot find anything official. We are going to switch to the normal deployments via Azure Portal.
