### ISSUE TITLE
Deployment Center Sync Failing

### ISSUE THREAD

**Issue by n2x4** [solvsoftware/Ghost-Azure#46]
Site has been running great for about a year - this is just my second time syncing and this time it failed.  Log attached, not sure where to start troubleshooting.  There's an error for migratorconfig.js missing but I've verified from console that the file exists and has content.

Any Suggestions?

[deploymenterror.txt](https://github.com/RadoslavGatev/Ghost-Azure/files/6889578/deploymenterror.txt)

**Comment by RadoslavGatev** [comment]
I've just synced a couple of blogs and it works fine.
